actors = [
    {
        "category": "Solo",
        "name": "Kit Connor",
        "image_2": "/images/kit2.jpg",
        "image": "/images/kit.jpg",
        "description": "Born：March 8, 2004 in London, England, UK",
        "description_long": "The youngest, Kit, 18, from London, was still at school during filming. Juggling this with schoolwork was a challenge, he admits. “We were working long hours, you know? Twelve hours a day. So, it meant that I did have some work to do to try and keep up.” Yet, as the most experienced actor in the lead cast, with 10 years experience on film sets, it’s a balancing act he’s had to master before. His previous credits include portraying a young Sir Elton John in 2019’s Rocketman, and providing the voice of Lyra Belacqua’s dæmon Pantalaimon in the BBC’s Philip Pullman adaptation, His Dark Materials. Despite the hard work, though, he wouldn’t change a thing. “I don’t regret it at all, to be honest, because I think that doing Heartstopper was one of the most rewarding jobs I’ve ever done,” he shares.",
        "owner_id": 2,
    },
    {
        "category": "Solo",
        "name": "Joe Locke",
        "image_2": "/images/joe2.jpg",
        "image": "/images/joe.jpg",
        "description": "Born：September 24, 2003 in Douglas, Isle of Man",
        "description_long": "As a young gay man, Joe, who is 18 and from the Isle of Man, compares his schooldays with what Charlie goes through.“I think that with queer people there’s a universal experience of school that everyone sort of relates to, but then there are differences,” he says.He expands on the topic, “I never would say I was bullied. There was only a handful of people I can think of who ever said anything bad to me. Charlie really struggles with that. I think going to an all-boys school probably comes with its differences. I went to a co-ed state school, and I had more friends who were girls than boys. I think it would have been difficult for Charlie, especially in that situation.”This isn’t to say that Charlie is weak. There’s an inherent strength to him that queer people of all ages will identify with.",
        "owner_id": 2,
    },
    {
        "category": "Solo",
        "name": "William Gao",
        "image_2": "/images/will1.jpg",
        "image": "/images/will.jpg",
        "description": "Born：2002 or 2003 (age 19–20)",
        "description_long": "Will, 19, also from London, describes how hours before we met during Attitude’s set visit, he’d been taking a three-hour Chinese writing exam. “It was absolute chaos,” he laughs, agreeing that it was quite a shift going from school work to acting. “Looking back, it was a really crazy, intense time. I think I dealt with it OK. And I was happy with my results.” ",
        "owner_id": 2,
    },
    {
        "category": "Solo",
        "name": "Yasmin Finney",
        "image_2": "/images/yasmin2.jpg",
        "image": "/images/yasmin.jpg",
        "description": "Born：30 August 2003 (age 19)",
        "description_long": "18-year-old Yasmin and I are sat in two large chairs living out our Oprah Winfrey-Meghan Markle interview fantasy (“Were you silent or were you silenced?”). Manchester-born Yasmin probably relates to her character more than anyone else because both are trans people of colour. “When does that ever happen?” she asks, indirectly commenting on the state of LGBTQ+ representation in the media, before listing her favourite things about Elle.",
        "owner_id": 2,
    },
    {
        "category": "Couple",
        "name": "Kit & Joe",
        "image_2": "/images/couple1_1.jpg",
        "image": "/images/couple1.jpg",
        "description": "It’s clear that the webcomic has been closely studied, with entire panels retold on screen. Another key factor in ensuring the series accurately interpreted the comic was Alice’s presence on set. You might imagine that, for the cast, having the creator of the world you’re trying to bring to life present might be a daunting prospect.",
        "description_long": "In the first couple of volumes from the Heartstopper webcomic series, we meet Charlie after he has come out and is at ease with that element of his identity. It’s meeting Charlie that prompts Nick to embark on his own journey of self-discovery. Kit offers his perspective of the role he plays. “I think the beauty of the way that Nick is written is that the inner conflict in Nick’s mind is, I think, present in everyone’s life at some point,” he says. “Everyone has experienced a point where they’re not really sure what they’re expected to be and what they’re meant to be. And that is one of the biggest things about his story arc: overcoming the expectations within himself, that he thinks people have of him, and that others do have of him. His friends assume he’s straight and there’s no way that he could be anything else. I think everyone can relate to that. I certainly can.” ",
        "owner_id": 1,
    },
    {
        "category": "Couple",
        "name": "Will & Yaz",
        "image_2": "/images/couple2_2.jpg",
        "image": "/images/couple2.jpg",
        "description": "Further to this, a set of scenes which see Tao grow wary of a widening gap between him and Charlie as the latter moves closer to Nick — who unsurprisingly Tao shows little fondness for — reminds Will of being separated from his own school friends. ",
        "description_long": "“I liked her vulnerability, her shyness, her confidence, and her ability to be unapologetically herself,” she says. “We both moved schools, although she went to an all-girls school and I just went to another [mixed] school. I don’t think I would be as confident to move to an all-girls school, so I have to give it to her. She’s got the confidence, honey, she’s such a bodacious, strong, empowering character. And I hope that when the audience sees her on screen, they’ll see themselves represented, and they’ll see someone they can look up to.”For Will, Tao’s fear of change was something he could easily tap into. “I’ve had that numerous times in my life where, even now, with this show coming out, this time last year I thought I was just going to go to drama school and figure things out, maybe go travelling. But it has been a big change. And it’s going to be a big change in my life. And in aspects like that I really relate to Tao.”",
        "owner_id": 1,
    },
    {
        "category": "Group",
        "name": "The Group",
        "image_2": "/images/group1_2.jpg",
        "image": "/images/group1.jpg",
        "description": "Renew your home with the trendy Silvia lamp in white designed by the Danish brand Umage / Vita. Silvia is a lampshade made of polypropylene.",
        "description_long": "The story of two British teens, Nick Nelson and Charlie Spring, at an all-boys grammar school. Charlie, a high-strung, openly gay overthinker, and Nick, a cheerful, soft-hearted rugby player, one day are made to sit together in class. Their friendship quickly becomes something more for openly gay Charlie, but he initially does not believe he has a chance with Nick, but love works in surprising ways, with Nick more interested in Charlie than either of them realized. Heartstopper is about love, friendship, and loyalty. It encompasses all the small stories of Nick and Charlie's lives that together make something larger.",
        "owner_id": 1,
    },
    {
        "category": "Group",
        "name": "Four of us.",
        "image_2": "/images/group2_2.jpg",
        "image": "/images/group2.jpg",
        "description": "The charming Luciakör electric advent candle holder is a Christmas classic from Star Trading. This candle holder is made of painted wood ...",
        "description_long": "The story of two British teens, Nick Nelson and Charlie Spring, at an all-boys grammar school. Charlie, a high-strung, openly gay overthinker, and Nick, a cheerful, soft-hearted rugby player, one day are made to sit together in class. Their friendship quickly becomes something more for openly gay Charlie, but he initially does not believe he has a chance with Nick, but love works in surprising ways, with Nick more interested in Charlie than either of them realized. Heartstopper is about love, friendship, and loyalty. It encompasses all the small stories of Nick and Charlie's lives that together make something larger.",
        "owner_id": 1,
    },
    {
        "category": "Group",
        "name": "Milkshake's Yummy!",
        "image_2": "/images/group3_2.jpeg",
        "image": "/images/group3.jpg",
        "description": "The High Dot stool leather from Fritz Hansen is a stable little seat made from premium leather and three legs of quality steel.",
        "description_long": "The story of two British teens, Nick Nelson and Charlie Spring, at an all-boys grammar school. Charlie, a high-strung, openly gay overthinker, and Nick, a cheerful, soft-hearted rugby player, one day are made to sit together in class. Their friendship quickly becomes something more for openly gay Charlie, but he initially does not believe he has a chance with Nick, but love works in surprising ways, with Nick more interested in Charlie than either of them realized. Heartstopper is about love, friendship, and loyalty. It encompasses all the small stories of Nick and Charlie's lives that together make something larger.",
        "owner_id": 1,
    },
    {
        "category": "Sences",
        "name": "Love being with you.",
        "image_2": "/images/series1_2.png",
        "image": "/images/series1.jpg",
        "description": "They know just when to expand the drama, when to deliver the emotional pay-offs, and how to ensure the audience remains satisfied. And this is pretty much all the time, because Heartstopper is a show that aims to deliver everything you could want from this story and more.",
        "description_long": "Writer Alice Oseman and director Euros Lyn understand this story inside out, and they know just when to expand the drama, when to deliver the emotional pay-offs, and how to ensure the audience remains satisfied. And this is pretty much all the time, because Heartstopper is a show that aims to deliver everything you could want from this story and more.",
        "owner_id": 1,
    },
    {
        "category": "Sences",
        "name": "Are we BTF?",
        "image_2": "/images/series2_2.jpg",
        "image": "/images/series2.jpeg",
        "description": "The Satake Kuro Chopper is a handmade and rough forged knife of exceptional quality. It has been developed with a focus on sharpness, precision ",
        "description_long": "While Charlie and Nick are the main focus of this story, there are other tales being told including a side story involving a lesbian couple, and a burgeoning romance between two friends, one of whom is transgender. These are stories that I expect will come into greater focus if there is a second season, and I believe they will continue to be told with the same level of care as shown here.",
        "owner_id": 1,
    },
    {
        "category": "Sences",
        "name": "So bad at playing drums.",
        "image_2": "/images/series3_2.jpg",
        "image": "/images/series3.jpg",
        "description": "There are other tales being told including a side story involving a lesbian couple, and a burgeoning romance between two friends, one of whom is transgender. ",
        "description_long": "Central to this entire show is the relationship between Charlie and Nick, as played by Joe Locke and Kit Connor respectively. These two actors are perfectly cast in this series, and do an excellent job of bringing their small screen counterparts to life.",
        "owner_id": 1,
    }
]